// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RateThisBook.Data
{
    public partial class Books
    {
        public int BookRef { get; set; }
        public string BookTitle { get; set; }
        public string Authors { get; set; }
        public string Summary { get; set; }
    }
}